# Generated by Django 3.1.1 on 2021-04-01 16:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=350)),
                ('isSuperUser', models.BooleanField(default=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportType', models.BooleanField()),
                ('description', models.TextField()),
                ('deed', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporterApp.category')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporterApp.account')),
                ('impact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporterApp.impact')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporterApp.location')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
