# Generated by Django 3.1.1 on 2021-04-01 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reporterApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='Category',
            new_name='category',
        ),
        migrations.AddField(
            model_name='report',
            name='report_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
