# Generated by Django 3.1.1 on 2021-04-04 07:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reporterApp', '0002_auto_20210401_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
